name: tassty_food_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  go_router: ^16.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
  fonts:
    - family: ApfelGrotezk
      fonts:
        - asset: assets/fonts/apfelGrotezk/ApfelGrotezk-Fett.otf
          weight: 700
        - asset: assets/fonts/apfelGrotezk/ApfelGrotezk-Mittel.otf
          weight: 500
        - asset: assets/fonts/apfelGrotezk/ApfelGrotezk-Regular.otf
          weight: 400

    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/plusJakartaSans/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/plusJakartaSans/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/plusJakartaSans/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/plusJakartaSans/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/plusJakartaSans/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/plusJakartaSans/PlusJakartaSans-SemiBold.ttf
          weight: 600
